[package]
name = "Examples"
version = "0.0.0"

[addresses]
HelloBlockchain = "_"

[dependencies]
# AptosFramework = { local = "../../framework/aptos-framework" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
