[package]
name = "managed_coin"
version = "0.0.0"

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
core_resources = "0xA550C18"
vm_reserved = "0x0"
Deployment  = "0x1337"
Owner = "0x1338"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
# MoveStdlib = { local = "../move-stdlib" }