import { Grid, GridItem } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid templateColumns="repeat(5, 1fr)" gap={3}>
        <GridItem colSpan={5} h="10" bg="blue.500" />
        <GridItem colSpan={1} h="10" bg="blue.500" />
        <GridItem colSpan={1} h="10" bg="blue.500" />
        <GridItem colSpan={2} h="10" bg="blue.500" />
        <GridItem colSpan={1} h="10" bg="blue.500" />
      </Grid>
    </>
  );
};

export default Home;
