import { Grid, GridItem } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import {
  Balance,
  OrderBook,
  PriceChart,
  Trades,
  NewOrder,
  MyTransactions,
} from "../components/index";
import { Navbar } from "../components/layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        templateColumns="repeat(5, 1fr)"
        templateRows="5vh repeat(2, 45vh)"
        gap={3}
      >
        <GridItem
          gridRow="1 / span 1"
          gridColumn="span 5"
          h="5vh"
          minHeight="10"
          bg="blue.500"
        >
          <Navbar />
        </GridItem>

        <GridItem gridRow="2 / 3" gridColumn="1 / span 1" bg="blue.500">
          <Balance />
        </GridItem>

        <GridItem
          gridRow="2 / 4"
          gridColumn="2 / 3"
          bg="blue.500"
          // overflow="auto"
        >
          <OrderBook />
        </GridItem>

        <GridItem gridRow="2 / span 1" gridColumn="3 / span 2" bg="blue.500">
          <PriceChart />
        </GridItem>

        <GridItem gridRow="2 / span 2" gridColumn="5" bg="blue.500">
          <Trades />
        </GridItem>

        <GridItem gridRow="3 / span 1" gridColumn="1" bg="blue.500">
          <NewOrder />
        </GridItem>

        <GridItem gridRow="3 / 4" gridColumn="3 / span 2" bg="blue.500">
          <MyTransactions />
        </GridItem>
      </Grid>
    </>
  );
};

export default Home;
