import { Grid, GridItem } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import {
  Balance,
  OrderBook,
  Card3,
  Card4,
  Card5,
  Card6,
} from "../components/index";
import { Navbar } from "../components/layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid templateColumns="repeat(5, 1fr)" gap={3}>
        <GridItem colSpan={5} rowSpan={1} h="5vh" minHeight="10" bg="blue.500">
          <Navbar />
        </GridItem>

        <GridItem colSpan={1} rowSpan={1} bg="blue.500">
          <Balance />
        </GridItem>

        <GridItem colSpan={1} rowSpan={2} h="50vh" bg="blue.500">
          <OrderBook />
        </GridItem>

        <GridItem colSpan={2} rowSpan={1} h="50vh" bg="blue.500">
          <Card3 />
        </GridItem>

        <GridItem colSpan={1} rowSpan={2} h="50vh" bg="blue.500">
          <Card4 />
        </GridItem>

        <GridItem colSpan={1} rowSpan={1} h="40vh" bg="blue.500">
          <Card5 />
        </GridItem>

        <GridItem colSpan={2} rowSpan={1} h="40vh" bg="blue.500">
          <Card6 />
        </GridItem>
      </Grid>
    </>
  );
};

export default Home;
