[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_fullstack = "GVU4ACeyPutnT8FzbgerrANxoYAxw8k4irCRPbgxVnKe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/tobias/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
